name: CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Find the Maven pom anywhere in the repo
      - name: Detect Maven project
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          FOUND="$(find . -maxdepth 5 -type f -name pom.xml | head -n1)"
          if [ -z "$FOUND" ]; then
            echo "No pom.xml found"; exit 1
          fi
          DIR="$(dirname "$FOUND")"
          echo "POM_DIR=$DIR" >> $GITHUB_ENV
          echo "Using Maven project at: $DIR"

      - name: Build & test (Maven)
        shell: bash
        run: |
          cd "$POM_DIR"
          mvn -B clean verify
