name: Deploy Dev
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  STACK_NAME: discra-api-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Find the SAM template anywhere in the repo
      - name: Detect SAM template
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          echo "Workspace: $GITHUB_WORKSPACE"
          FOUND="$(find . -maxdepth 5 -type f -name template.yaml | head -n1)"
          if [ -z "$FOUND" ]; then
            echo "No template.yaml found"; exit 1
          fi
          DIR="$(dirname "$FOUND")"
          echo "Template: $FOUND"
          echo "ProjectDir: $DIR"
          echo "TEMPLATE_PATH=$FOUND" >> $GITHUB_ENV
          echo "PROJECT_DIR=$DIR"     >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::422814825143:role/GitHubActions-Discra-Deploy-Dev
          role-session-name: discra-deploy-dev

      - name: SAM validate
        shell: bash
        run: sam validate --lint -t "$TEMPLATE_PATH"

      - name: Build (SAM)
        shell: bash
        run: sam build -t "$TEMPLATE_PATH" --parallel

      - name: Deploy (SAM)
        shell: bash
        run: |
          sam deploy \
            -t "$TEMPLATE_PATH" \
            --stack-name "$STACK_NAME" \
            --region "$AWS_REGION" \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3




