name: Deploy Dev
on:
  push:
    branches: [ main ]

permissions:
  id-token: write     # required for OIDC
  contents: read

env:
  AWS_REGION: us-east-1            # change if needed
  STACK_NAME: discra-api-dev
  WORKING_DIR: discra          # folder that contains template.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::422814825143:role/GitHubActions-Discra-Deploy-Dev  # <-- paste your Role ARN
          role-session-name: discra-deploy-dev
          
      - name: Who am I? (STS)
        run: aws sts get-caller-identity


      - name: SAM validate
        working-directory: ${{ env.WORKING_DIR }}
        run: sam validate --lint

      - name: Build (SAM)
        working-directory: ${{ env.WORKING_DIR }}
        run: sam build --parallel

      - name: Deploy (SAM)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3

