AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Discra API - dual-stack migration (Java + Python backend)

Parameters:
  Version:
    Type: String
    Default: 0.0.1-tracer
    Description: Deployed version string (use Git SHA in CI)
  AdminToken:
    Type: String
    NoEcho: true
    Description: Admin token for /admin routes (dev only)
  CognitoUserPoolId:
    Type: String
    Default: us-east-1_examplepool
    Description: Cognito User Pool ID used by API Gateway JWT authorizer
  CognitoAppClientId:
    Type: String
    Default: exampleclientid
    Description: Cognito App Client ID (JWT audience)
  LocationRouteCalculatorName:
    Type: String
    Default: ""
    Description: Optional Amazon Location route calculator name for matrix calls
  StripeSecretKey:
    Type: String
    Default: ""
    NoEcho: true
    Description: Optional Stripe secret key for subscription seat updates
  StripeWebhookSecret:
    Type: String
    Default: ""
    NoEcho: true
    Description: Optional Stripe webhook signing secret
  StripeDispatcherPriceId:
    Type: String
    Default: ""
    Description: Optional Stripe price id for dispatcher seats
  StripeDriverPriceId:
    Type: String
    Default: ""
    Description: Optional Stripe price id for driver seats
  OrdersWebhookToken:
    Type: String
    Default: ""
    NoEcho: true
    Description: Shared secret for external order-ingest webhook

Globals:
  Function:
    Runtime: java21
    MemorySize: 512
    Timeout: 10
    Tracing: Active
    Architectures: [ x86_64 ]
    Environment:
      Variables:
        VERSION: !Ref Version
    Tags:
      App: Discra
      Env: dev
      Owner: Cody
  Api:
    Cors:
      AllowOrigins: "'*'"
      AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
      AllowHeaders: "'content-type,x-admin-token,authorization,x-correlation-id'"

Resources:
  DiscraApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      Auth:
        Authorizers:
          CognitoJwtAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}"
              audience:
                - !Ref CognitoAppClientId
      Tags: { App: Discra, Env: dev }

  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "discra-organizations-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "discra-users-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  PodArtifactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "discra-pod-artifacts-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: pod_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: pod_id
          KeyType: RANGE
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  DriverLocationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "discra-driver-locations-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: driver_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: driver_id
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires_at_epoch
        Enabled: true
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  SeatSubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "discra-seat-subscriptions-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  SeatInvitationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "discra-seat-invitations-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: invitation_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: invitation_id
          KeyType: RANGE
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  PodArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - POST
              - PUT
            AllowedHeaders:
              - "*"
            MaxAge: 300
      Tags:
        - Key: App
          Value: Discra
        - Key: Env
          Value: dev

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.discra.api.HealthHandler::handleRequest
      Events:
        HealthGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /health
            Method: GET
      Tags: { App: Discra, Env: dev }

  VersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.discra.api.VersionHandler::handleRequest
      Events:
        VersionGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /version
            Method: GET
      Tags: { App: Discra, Env: dev }

  AdminPingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.discra.api.AdminPingHandler::handleRequest
      Environment:
        Variables:
          ADMIN_TOKEN: !Ref AdminToken
      Events:
        AdminPingGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /admin/ping
            Method: GET
      Tags: { App: Discra, Env: dev }

  BackendApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: backend
      Handler: app.handler
      MemorySize: 512
      Timeout: 15
      Tracing: Active
      Environment:
        Variables:
          VERSION: !Ref Version
          COGNITO_ISSUER: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}"
          COGNITO_AUDIENCE: !Ref CognitoAppClientId
          JWT_VERIFY_SIGNATURE: "true"
          ORGANIZATIONS_TABLE: !Ref OrganizationsTable
          USERS_TABLE: !Ref UsersTable
          POD_BUCKET_NAME: !Ref PodArtifactsBucket
          POD_ARTIFACTS_TABLE: !Ref PodArtifactsTable
          POD_UPLOAD_URL_EXPIRES_SECONDS: "300"
          DRIVER_LOCATIONS_TABLE: !Ref DriverLocationsTable
          DRIVER_LOCATION_TTL_SECONDS: "7200"
          LOCATION_ROUTE_CALCULATOR_NAME: !Ref LocationRouteCalculatorName
          USE_IN_MEMORY_ROUTE_MATRIX: "false"
          ROUTE_OPTIMIZATION_TIMEOUT_SECONDS: "5"
          SEAT_SUBSCRIPTIONS_TABLE: !Ref SeatSubscriptionsTable
          SEAT_INVITATIONS_TABLE: !Ref SeatInvitationsTable
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
          STRIPE_DISPATCHER_PRICE_ID: !Ref StripeDispatcherPriceId
          STRIPE_DRIVER_PRICE_ID: !Ref StripeDriverPriceId
          ORDERS_WEBHOOK_TOKEN: !Ref OrdersWebhookToken
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !GetAtt OrganizationsTable.Arn
              - !GetAtt UsersTable.Arn
              - !GetAtt PodArtifactsTable.Arn
              - !GetAtt DriverLocationsTable.Arn
              - !GetAtt SeatSubscriptionsTable.Arn
              - !GetAtt SeatInvitationsTable.Arn
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:AbortMultipartUpload
            Resource: !Sub "${PodArtifactsBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - geo:CalculateRouteMatrix
            Resource: "*"
      Events:
        BackendHealthGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /backend/health
            Method: GET
        BackendVersionGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /backend/version
            Method: GET
        BackendStripeWebhookPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /backend/webhooks/stripe
            Method: POST
        BackendOrdersWebhookPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /backend/webhooks/orders
            Method: POST
        BackendProtectedProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscraApi
            Path: /backend/{proxy+}
            Method: ANY
            Auth:
              Authorizer: CognitoJwtAuthorizer
      Tags: { App: Discra, Env: dev }

Outputs:
  ApiId:
    Description: HTTP API ID
    Value: !Ref DiscraApi

  ApiEndpoint:
    Description: Base URL for the HTTP API (no stage suffix)
    Value: !GetAtt DiscraApi.ApiEndpoint

  HealthUrl:
    Description: Full URL for GET /health
    Value: !Sub
      - "${Endpoint}/dev/health"
      - { Endpoint: !GetAtt DiscraApi.ApiEndpoint }

  VersionUrl:
    Description: Full URL for GET /version
    Value: !Sub
      - "${Endpoint}/dev/version"
      - { Endpoint: !GetAtt DiscraApi.ApiEndpoint }

  AdminPingUrl:
    Description: Full URL for GET /admin/ping
    Value: !Sub
      - "${Endpoint}/dev/admin/ping"
      - { Endpoint: !GetAtt DiscraApi.ApiEndpoint }

  BackendHealthUrl:
    Description: Full URL for GET /backend/health
    Value: !Sub
      - "${Endpoint}/dev/backend/health"
      - { Endpoint: !GetAtt DiscraApi.ApiEndpoint }

  BackendVersionUrl:
    Description: Full URL for GET /backend/version
    Value: !Sub
      - "${Endpoint}/dev/backend/version"
      - { Endpoint: !GetAtt DiscraApi.ApiEndpoint }

  OrdersWebhookUrl:
    Description: Full URL for POST /backend/webhooks/orders
    Value: !Sub
      - "${Endpoint}/dev/backend/webhooks/orders"
      - { Endpoint: !GetAtt DiscraApi.ApiEndpoint }

  OrganizationsTableName:
    Description: DynamoDB table for tenant organization metadata
    Value: !Ref OrganizationsTable

  UsersTableName:
    Description: DynamoDB table for org users synced from Cognito claims
    Value: !Ref UsersTable

  PodArtifactsTableName:
    Description: DynamoDB table for proof-of-delivery metadata
    Value: !Ref PodArtifactsTable

  PodArtifactsBucketName:
    Description: S3 bucket for POD photos/signatures uploads
    Value: !Ref PodArtifactsBucket

  DriverLocationsTableName:
    Description: DynamoDB table for latest driver GPS locations
    Value: !Ref DriverLocationsTable

  SeatSubscriptionsTableName:
    Description: DynamoDB table for Stripe subscription + seat limits per org
    Value: !Ref SeatSubscriptionsTable

  SeatInvitationsTableName:
    Description: DynamoDB table for pending/accepted role invitations
    Value: !Ref SeatInvitationsTable



