name: Pilot Bug Report
description: Report a defect found during pilot testing
title: "[Pilot Bug]: "
labels:
  - bug
  - pilot
body:
  - type: dropdown
    id: role
    attributes:
      label: Role
      description: Which role was affected?
      options:
        - Admin
        - Dispatcher
        - Driver
        - Multiple
    validations:
      required: true

  - type: dropdown
    id: surface
    attributes:
      label: Surface
      description: Where did this happen?
      options:
        - Admin/Dispatcher Web UI
        - Driver Web UI
        - Mobile App (Expo)
        - API/Webhook
        - Other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Stack/stage and region (example: discra-api-dev us-east-1)
      placeholder: discra-api-dev us-east-1
    validations:
      required: true

  - type: input
    id: endpoint_or_page
    attributes:
      label: Endpoint or page
      description: API path or UI route where the issue appears
      placeholder: /backend/orders or /backend/ui/admin
    validations:
      required: true

  - type: input
    id: correlation
    attributes:
      label: Correlation data
      description: Request ID, order ID, user ID, or timestamp
      placeholder: request-id / order-id / timestamp

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - P0 - blocking
        - P1 - high
        - P2 - medium
        - P3 - low
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact steps, including inputs
      placeholder: |
        1. Login as Dispatcher
        2. Open order queue
        3. Bulk-assign selected orders
        4. Observe failure ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: Logs/screenshots
      description: Include API response snippets, screenshots, or stack traces

